name: BUILD

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download pkglist
      uses: actions/download-artifact@v2
      with:
        name: pkglist
    - uses: ./
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pkglist
        path: pkglist.txt
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*/*.pkg.tar.zst, ./*/*/*.pkg.tar.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
