name: BUILD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
    # - uses: DuckSoft/build-aur-action@master
      # with:
        # repo-name: vapoursynth-editor
    
    - run: find ./
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*/*.zst, ./*/*/*.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
