name: BUILD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
    
    - uses: ncipollo/release-action@main
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*/*.zst, ./*/*/*.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
